import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {NeonAuthUIProvider} from "@neondatabase/auth-ui";
import {createAuthClient} from "@neondatabase/auth";
import {NeonAuthProvider} from "@/providers/neon-auth-ui-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

      <NeonAuthProvider>
        <body className="min-h-full flex flex-col bg-background text-foreground">{children}</body>
      </NeonAuthProvider>

    </html>
  );
}
